### ISSUE TITLE
Progress bar state for new books

### ISSUE THREAD

**Issue by GianniCarlo** [harrisi/bookplayerweb#23]
With the current state, where playback does not start automatically, when I tap a new book without a current time set, the progress bar is set to 0 and the knob is positioned at the middle, I'm guessing that this state could stay like this while the book is buffering if it autoplayed on selection

<img width="1205" alt="Screenshot 2023-10-25 at 21 10 58" src="https://github.com/harrisi/bookplayerweb/assets/14112819/bc9d099e-391b-4bfa-8871-415fcc6abb7f">

**Comment by harrisi** [comment]
Interesting. What browser?

**Comment by harrisi** [comment]
Also, by "without a current time set", do you mean in the database, the `currentTime` field is `NULL`?

**Comment by GianniCarlo** [comment]
currently happens on both Opera and Safari

**Comment by GianniCarlo** [comment]
> Also, by "without a current time set", do you mean in the database, the currentTime field is NULL?

Yup on the DB I can confirm that the books that this happens to, have the `actual_time` as NULL as I've never played them before
