### ISSUE TITLE
Formatting for current time when it's below a minute

### ISSUE THREAD

**Issue by GianniCarlo** [harrisi/bookplayerweb#24]
I think when current time is below 1 minute, we should still show the format of 00:XX (same thing for duration when we add the remaining time preference)

**Comment by harrisi** [comment]
Yup, I was thinking the `currentTime` and `duration` should match in terms of length, so if it's over an hour long they both are `HH:MM:SS`, but if they're less than an hour, they both show `MM:SS`. Not sure if it should even be an option to show just `SS`.

**Comment by harrisi** [comment]
I opted to just always show at least MM:SS for now.
